export const TYPES = {
    GET_USERS_START: "GET_USERS_START",
    GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
    GET_USERS_FAILURE: "GET_USERS_FAILURE",
    UPLOAD_USER_START: "UPLOAD_USER_START",
    UPLOAD_USER_SUCCESS: "UPLOAD_USER_SUCCESS",
    UPLOAD_USER_FAILURE: "UPLOAD_USER_FAILURE",
    UPDATE_USER_START: "UPDATE_USER_START",
    UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
    UPDATE_USER_FAILURE: "UPDATE_USER_FAILURE",
    DELETE_USER_START: "DELETE_USER_START",
    DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
    DELETE_USER_FAILURE: "DELETE_USER_FAILURE",

}