export const TYPES = {
    GET_MOVIES_START: "GET_MOVIES_START",
    GET_MOVIES_SUCCESS: "GET_MOVIES_SUCCESS",
    GET_MOVIES_FAILURE: "GET_MOVIES_FAILURE",
    DELETE_MOVIE_START: "DELETE_MOVIE_START",
    DELETE_MOVIE_SUCCESS: "DELETE_MOVIE_SUCCESS",
    DELETE_MOVIE_FAILURE: "DELETE_MOVIE_FAILURE",
    UPLOAD_MOVIE_START: "UPLOAD_MOVIE_START",
    UPLOAD_MOVIE_SUCCESS: "UPLOAD_MOVIE_SUCCESS",
    UPLOAD_MOVIE_FAILURE: "UPLOAD_MOVIE_FAILURE",
    UPDATE_MOVIE_START: "UPDATE_MOVIE_START",
    UPDATE_MOVIE_SUCCESS: "UPDATE_MOVIE_SUCCESS",
    UPDATE_MOVIE_FAILURE: "UPDATE_MOVIE_FAILURE",
}
