export const TYPES = {
  GET_LISTS_START: "GET_LISTS_START",
  GET_LISTS_SUCCESS: "GET_LISTS_SUCCESS",
  GET_LISTS_FAILURE: "GET_LISTS_FAILURE",
  DELETE_LISTS_START: "DELETE_LISTS_START",
  DELETE_LISTS_SUCCESS: "DELETE_LISTS_SUCCESS",
  DELETE_LISTS_FAILURE: "DELETE_LISTS_FAILURE",
  UPLOAD_LIST_START: "UPLOAD_LIST_START",
  UPLOAD_LIST_SUCCESS: "UPLOAD_LIST_SUCCESS",
  UPLOAD_LIST_FAILURE: "UPLOAD_LIST_FAILURE",
  UPDATE_LIST_START: "UPDATE_LIST_START",
  UPDATE_LIST_SUCCESS: "UPDATE_LIST_SUCCESS",
  UPDATE_LIST_FAILURE: "UPDATE_LIST_FAILURE",
}
